Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@berlintz 
iranee
/
qnap-alist-webdav
Public
Fork your own copy of iranee/qnap-alist-webdav
Code
Issues
3
Pull requests
1
Actions
Projects
Security
Insights
使用Github Action自动构建 #19
 Open
tychenjiajun wants to merge 32 commits into iranee:main from tychenjiajun:main
+109 −1 
 Conversation 3
 Commits 32
 Checks 0
 Files changed 12
 Open
使用Github Action自动构建
#19
File filter 
 
Create blank.yml
@tychenjiajuntychenjiajun committed 2 weeks ago 
commit 571d1fc83ef3f2aaeb0596c0132af9ce8b83d1b6
 47  
.github/workflows/blank.yml
@@ -0,0 +1,47 @@
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: apt
        run: |
          apt-get update -y && \
          apt-get install -y --no-install-recommends \
          git-core \
          ca-certificates
      
      # Runs a set of commands using the runners shell
      - name: clone
        run: git clone https://github.com/qnap-dev/QDK.git


      # Runs a set of commands using the runners shell
      - name: qdk
        run: cd /QDK && ./InstallToUbuntu.sh install

      # Runs a set of commands using the runners shell
      - name: export
        run: export PATH="/usr/share/QDK/bin:${PATH}"
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
使用Github Action自动构建 by tychenjiajun · Pull Request #19 · iranee/qnap-alist-webdav
